name: Build Binary on Release Branch

on:
  pull_request:
    branches:
      - master  # Trigger when a pull request is merged into master
    types: [closed]  # Only run when the pull request is closed

  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Replace with your required version

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build Project
      run: |
        platformio run

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: .pio/build/lolin_s2_mini/firmware.bin  # Replace with the actual path to your binary file
