name: Manual Build Binary

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with your required version

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Generate Datetime Version
      id: generate_version
      run: |
        VERSION=$(date +'%y-%m-%d-%H_%M')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Project
      run: |
        platformio run

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: firmware-${{ env.VERSION }}
        path: build/firmware-${{ env.VERSION }}.bin  # Replace with the actual path to your binary file
